//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamClient.VLM.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamClient.VLM.Localization.Res", typeof(Res).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bitrate.
        /// </summary>
        public static string ABitrate {
            get {
                return ResourceManager.GetString("ABitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In kbit/sec, recommended is 96.
        /// </summary>
        public static string ABitrateHint {
            get {
                return ResourceManager.GetString("ABitrateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Channels.
        /// </summary>
        public static string AChannels {
            get {
                return ResourceManager.GetString("AChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended is 2.
        /// </summary>
        public static string AChannelsHint {
            get {
                return ResourceManager.GetString("AChannelsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Codec.
        /// </summary>
        public static string ACodec {
            get {
                return ResourceManager.GetString("ACodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only mp3 is supported at the moment.
        /// </summary>
        public static string ACodecHint {
            get {
                return ResourceManager.GetString("ACodecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced error message: .
        /// </summary>
        public static string AdvancedErrorMessage {
            get {
                return ResourceManager.GetString("AdvancedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Sample Rate.
        /// </summary>
        public static string ASampleRate {
            get {
                return ResourceManager.GetString("ASampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended is 44100 or 48000.
        /// </summary>
        public static string ASampleRateHint {
            get {
                return ResourceManager.GetString("ASampleRateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        public static string Buffering {
            get {
                return ResourceManager.GetString("Buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching.
        /// </summary>
        public static string Caching {
            get {
                return ResourceManager.GetString("Caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with VLC failed..
        /// </summary>
        public static string CommunicationFailed {
            get {
                return ResourceManager.GetString("CommunicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually this indicates that the source is not available or not supported by VLC. Other reasons can be missing network connectivity or incorrect streaming settings..
        /// </summary>
        public static string CommunicationFailedHint {
            get {
                return ResourceManager.GetString("CommunicationFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually 8080.
        /// </summary>
        public static string ControlPortHintVLC {
            get {
                return ResourceManager.GetString("ControlPortHintVLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually 8011.
        /// </summary>
        public static string ControlPortHintWMV {
            get {
                return ResourceManager.GetString("ControlPortHintWMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using VLC version {0}. This version has known issues with file transcoding and will crash during playback. Please use Version 2.0.2 instead..
        /// </summary>
        public static string Error204 {
            get {
                return ResourceManager.GetString("Error204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames per second.
        /// </summary>
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended is 25 or 30 depending on source.
        /// </summary>
        public static string FPSHint {
            get {
                return ResourceManager.GetString("FPSHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD.
        /// </summary>
        public static string HD {
            get {
                return ResourceManager.GetString("HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended is 240.
        /// </summary>
        public static string HeightHint {
            get {
                return ResourceManager.GetString("HeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming from localhost is not supported.
        /// </summary>
        public static string HostHint {
            get {
                return ResourceManager.GetString("HostHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoStreamingConnection {
            get {
                return ResourceManager.GetString("NoStreamingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback failed.
        /// </summary>
        public static string PlaybackFailed {
            get {
                return ResourceManager.GetString("PlaybackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a transcoding profile depending on your hardware and connection speed.
        /// </summary>
        public static string PresetHint {
            get {
                return ResourceManager.GetString("PresetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because this is a streaming video player, position changes will not affect you phone. The change is sent to the VLC server and it will take up to 20 seconds before you see the new position your Windows Phone..
        /// </summary>
        public static string SeekHint {
            get {
                return ResourceManager.GetString("SeekHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Type.
        /// </summary>
        public static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only VLC is supported at the moment.
        /// </summary>
        public static string ServerTypeHint {
            get {
                return ResourceManager.GetString("ServerTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcoding Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Subtitle.
        /// </summary>
        public static string ShowSubtitle {
            get {
                return ResourceManager.GetString("ShowSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For good text readability choose a high transcoding profile.
        /// </summary>
        public static string ShowSubtitleHint {
            get {
                return ResourceManager.GetString("ShowSubtitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamingFailed.
        /// </summary>
        public static string StreamingFailed {
            get {
                return ResourceManager.GetString("StreamingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamingServerMissing.
        /// </summary>
        public static string StreamingServerMissing {
            get {
                return ResourceManager.GetString("StreamingServerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming Port.
        /// </summary>
        public static string StreamPort {
            get {
                return ResourceManager.GetString("StreamPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually 8012.
        /// </summary>
        public static string StreamPortHint {
            get {
                return ResourceManager.GetString("StreamPortHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Intel Quick Sync Video Encoder.
        /// </summary>
        public static string UseQSV {
            get {
                return ResourceManager.GetString("UseQSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Bitrate.
        /// </summary>
        public static string VBitrate {
            get {
                return ResourceManager.GetString("VBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In kbit/sec, recommended is 512.
        /// </summary>
        public static string VBitrateHint {
            get {
                return ResourceManager.GetString("VBitrateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Codec.
        /// </summary>
        public static string VCodec {
            get {
                return ResourceManager.GetString("VCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only h264 is supported at the moment.
        /// </summary>
        public static string VCodecHint {
            get {
                return ResourceManager.GetString("VCodecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoFailed.
        /// </summary>
        public static string VideoFailed {
            get {
                return ResourceManager.GetString("VideoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended is 400.
        /// </summary>
        public static string WidthHint {
            get {
                return ResourceManager.GetString("WidthHint", resourceCulture);
            }
        }
    }
}
