namespace XBMCRPC.Player.Property
{
   public enum Name
   {
       type,
       partymode,
       speed,
       time,
       percentage,
       totaltime,
       playlistid,
       position,
       repeat,
       shuffled,
       canseek,
       canchangespeed,
       canmove,
       canzoom,
       canrotate,
       canshuffle,
       canrepeat,
       currentaudiostream,
       audiostreams,
       subtitleenabled,
       currentsubtitle,
       subtitles,
       live,
   }
}
